Category.destroy_all
Photo.destroy_all
Ingredient.destroy_all
Product.destroy_all
CookingStep.destroy_all
Recipe.destroy_all
Admin.destroy_all

admin = Admin.create(email: 'admin@example.com', password: 'abcd1234')

cat1 = Category.create(name: 'maaltijd')
cat2 = Category.create(name: 'lunch')
cat3 = Category.create(name: 'snack')
cat4 = Category.create(name: 'dessert')
cat5 = Category.create(name: 'bijgerecht')
cat6 = Category.create(name: 'salade')
cat7 = Category.create(name: 'taart')
cat8 = Category.create(name: 'soep')
cat9 = Category.create(name: '1 persoons')
cat10 = Category.create(name: 'super snel')
cat11 = Category.create(name: 'vegan')
cat12 = Category.create(name: 'vegetarisch')
cat13 = Category.create(name: 'vis')
cat14 = Category.create(name: 'eieren')


product1 = Product.create(name: 'ongezoete sojayoghurt naturel')
product2 = Product.create(name: 'biologiche citroen')
product3 = Product.create(name: 'neutrale plantaardige olie')
product4 = Product.create(name: 'ahornsiroop')
product5 = Product.create(name: 'rijststroop')
product6 = Product.create(name: 'tarwebloem')
product7 = Product.create(name: 'bakpoeder')
product8 = Product.create(name: 'baksoda')
product9 = Product.create(name: 'zeezout')
product10 = Product.create(name: 'prei')
product11 = Product.create(name: 'spinazie')
product12 = Product.create(name: 'knoflook')
product13 = Product.create(name: 'oregano')
product14 = Product.create(name: 'ei')
product15 = Product.create(name: 'olijfolie')
product16 = Product.create(name: 'feta')
product17 = Product.create(name: 'tempeh')
product18 = Product.create(name: 'water')
product19 = Product.create(name: 'sojasaus')
product20 = Product.create(name: 'knoflookpoeder')
product21 = Product.create(name: 'zwarte peper')
product22 = Product.create(name: 'bolletjes')
product23 = Product.create(name: 'sla')
product24 = Product.create(name: 'tomaat')
product25 = Product.create(name: 'augurken')
product26 = Product.create(name: 'suikervrije mayonaise')
product27 = Product.create(name: 'suikervrije ketchup')
product28 = Product.create(name: 'walnoten')
product29 = Product.create(name: 'havermout')
product30 = Product.create(name: 'dadels')
product31 = Product.create(name: 'rauwe cacao')
product32 = Product.create(name: 'vanille')
product33 = Product.create(name: 'sinaasappel')
product34 = Product.create(name: 'kokosolie')
product35 = Product.create(name: 'pompoen')
product36 = Product.create(name: 'winterwortel')
product37 = Product.create(name: 'ui')
product38 = Product.create(name: 'gember')
product39 = Product.create(name: 'groentebouillon')
product40 = Product.create(name: 'rode paprika')
product41 = Product.create(name: 'bosui')
product42 = Product.create(name: 'peterselie')

cooking_step1 = CookingStep.create(description: 'Verwarm de oven voor op 175 C')
cooking_step2 = CookingStep.create(description: 'Vet een tulbandvorm in met een beetje olie en strooi er een dun laagje bloem in, klop overtollig bloem er weer uit.')
cooking_step3 = CookingStep.create(description: 'Meng in een kom de yoghurt met de rasp en het sap van de citroen. Roer goed door met een garde en laat het even staan.')
cooking_step4 = CookingStep.create(description: 'Zeef in een andere kom de bloem, het bakpoeder, de baksoda en het zout en roer door elkaar.')
cooking_step5 = CookingStep.create(description: 'Voeg de olie, ahorn siroop, en rijststroop toe aan de yoghurt en meng.')
cooking_step6 = CookingStep.create(description: 'Meng met een garde de bloem door het yoghurtmengsel. Het beslag wordt meteen dik en begint al met reizen door het bakpoeder en het citroensap dat op elkaar reageert.')
cooking_step7 = CookingStep.create(description: 'Spatel nu voorzichtig het beslag in de bakvorm en strijk aan de bovenkant glad.')
cooking_step8 = CookingStep.create(description: 'Bak de cake ongeveer 40 minuten, tot de bovenkant licht goudbruin is. Laat de cake 10 minuten afkoelen in de vorm en stort hem dan op een rooster om af te koelen.')
cooking_step9 = CookingStep.create(description: 'Was de prei, snij het donkergroene gedeelte eraf en snij de prei in ringetjes.')
cooking_step10 = CookingStep.create(description: 'Hak de knoflook fijn')
cooking_step11 = CookingStep.create(description: 'Bak in een stoofpannetje de prei in de olijfolie in een paar minuutjes gaar.')
cooking_step12 = CookingStep.create(description: 'Voeg de knoflook en oregano toe en bak een minuutje mee.')
cooking_step13 = CookingStep.create(description: 'Roer de spinazie door de prei en bak roerend mee tot de spinazie geslonken is.')
cooking_step14 = CookingStep.create(description: 'Maak twee kuiltjes voor de eieren en breek ze er één voor één in. Verkruimel de feta over de eieren en de groenten.')
cooking_step15 = CookingStep.create(description: 'Leg een deksel op de pan en laat het in ongeveer vijf minuten gaar worden.')
cooking_step16 = CookingStep.create(description: 'Snij de tempeh in plakjes van een 1/2 cm.')
cooking_step17 = CookingStep.create(description: 'Verwarm de olie in een koekenpan en bak hierin de tempeh aan beide kanten  goudbruin.')
cooking_step18 = CookingStep.create(description: 'Voeg het water, de sojasaus, ahornsiroop, knoflook en wat peper toe aan de tempeh.')
cooking_step19 = CookingStep.create(description: 'laat de tempeh nu zachtjes inkoken in 10 minuten tot al het vocht is verdampt. Keer de tempeh  halverwege een keer om.')
cooking_step20 = CookingStep.create(description: 'Snij de tomaat en augurk in plakjes.')
cooking_step21 = CookingStep.create(description: 'Besmeer de bolletjes aan beide kanten met een beetje mayonaise.')
cooking_step22 = CookingStep.create(description: 'Beleg de broodjes met sla, tomaat, de tempeh, ketchup en de augurk.')
cooking_step23 = CookingStep.create(description: 'Verwarm de oven voor op 180°C')
cooking_step24 = CookingStep.create(description: 'Vet de taartvorm in met een klein beetje olijfolie en leg een bakpapiertje op de bodem.')
cooking_step25 = CookingStep.create(description: 'Maal in een keukenmachine alle ingrediënten voor de bodem fijn, maar zo dat er wel nog een beetje structuur overblijft. Schraap tussendoor even langs de randen.')
cooking_step26 = CookingStep.create(description: 'Schep het deegmengsel in de taartvorm. Verdeel het met je handen gelijkmatig over de bodem en maak een klein opstaand randje.')
cooking_step27 = CookingStep.create(description: 'Bak de bodem ongeveer 15 minuten, of tot hij licht goudbruin is.')
cooking_step28 = CookingStep.create(description: 'Smelt de kokosolie in een klein pannetje op laag vuur.')
cooking_step29 = CookingStep.create(description: 'Maal alle ingrediënten voor de vulling in de keukenmachine tot een hele fijne pasta.')
cooking_step30 = CookingStep.create(description: 'Laat de bodem even afkoelen en verdeel de vulling er dan gelijkmatig overheen. Laat de taart een uurtje opstijven in de koelkast.')
cooking_step31 = CookingStep.create(description: 'Bestrooi de taart met wat extra cacao door een klein zeefje.')
cooking_step32 = CookingStep.create(description: 'Snij de pompoen in kwarten en schraap met een lepel de pitjes eruit.')
cooking_step33 = CookingStep.create(description: 'Als de schil mooi is kan je die eraan laten, anders schil je de pompoen met een dunschiller. Of je snijt de pompoen eerst in parten en dan snij je de schil eraf met een mes. Snij daarna de pompoen in stukken.')
cooking_step34 = CookingStep.create(description: 'Snij de wortel in plakken en de ui in halve maantjes.')
cooking_step35 = CookingStep.create(description: 'Hak de knoflook en de gember fijn.')
cooking_step36 = CookingStep.create(description: 'Verwarm in een grote pan 2 el olijfolie en bak hierin de ui glazig, voeg dan de knoflook en gember toe en bak 1 minuut mee. Voeg de pompoen en wortel toe en bak bak ook nog even mee.')
cooking_step37 = CookingStep.create(description: 'Giet de boullion over de groenten tot ze net onder staan en breng aan de kook.')
cooking_step38 = CookingStep.create(description: 'Laat de soep ongeveer 20 minuten zachtjes koken met een deksel op de pan. Proef aan het eind of de groenten goed gaar zijn.')
cooking_step39 = CookingStep.create(description: 'Terwijl de soep kookt snij je de paprika in reepjes en de bosui in ringetjes. Bak deze in 1 el olijfolie gaar, maar wel nog net knapperig. Breng aan het eind op smaak met zout en peper.')
cooking_step40 = CookingStep.create(description: 'Hak de peterselie fijn.')
cooking_step41 = CookingStep.create(description: 'Als de soep klaar is pureer je hem met een staafmixer. Breng eventueel op smaak met zout en peper.  Als de soep te dik is verdun hem dan met een beetje water en warm de soep nog even door.')
cooking_step42 = CookingStep.create(description: 'Schep de soep in kommen en garneer met de peterselie en de paprikareepjes met bosui.')

recipe1 = Recipe.create(title: 'Citroentulband', subtitle: 'Citroen en yoghurt =) dubbelfris.', cooking_time:   60, intro: 'Gelukkig is deze tulband ook lekker zoet, maar niet te, je kan er best een schepje citroenjam bij eten :-)', featured: true, published: true, cooking_steps: [cooking_step1, cooking_step2, cooking_step3, cooking_step4, cooking_step5, cooking_step6, cooking_step7, cooking_step8], categories: [cat4, cat7, cat14], admin: admin)

recipe2 = Recipe.create(title: 'Groene Shakshuka', subtitle: 'Een eiergerecht met groenten', cooking_time: 40, intro: 'Shakshuka is geen exotisch dansje of gerecht met kikkerbilletjes. Het is een eiergerecht met groenten wat veel gegeten wordt in het middenoosten. Je kan het eten als ontbijt, brunch, lunch en simpel diner, en het is supersnel klaar. Het is lekker met een dikke snee geroosterd zuurdesem brood.
Je kan de prei en spinazie ook vervangen door 2 sjalotjes en fijngesneden snijbiet.', featured: true, published: true, cooking_steps: [cooking_step9, cooking_step10, cooking_step11, cooking_step12, cooking_step13, cooking_step14, cooking_step15], categories: [cat1, cat2, cat10, cat12, cat14], persons: 2, admin: admin)

recipe3 = Recipe.create(title: 'Tempeh Burgers', subtitle: 'Makkelijk en snel', cooking_time: 30, intro: 'Heerlijke burgers die makkelijk te bereiden zijn. Eventueel kan je de sla vervangen door spinazie.', featured: true, published: true, cooking_steps: [cooking_step16, cooking_step17, cooking_step18, cooking_step19, cooking_step20, cooking_step21, cooking_step22], categories: [cat1, cat10, cat12], persons: 2, admin: admin)

recipe4 = Recipe.create(title: 'Chocolade-Ganachetaart met walnotenbodem', subtitle: 'Een diepe chocoladesmaak met sinaasappel en een brosse bodem.', cooking_time: 60, intro: 'Extra nodig: keukenmachine en taartvorm met losse bodem.', featured: false, published: false, cooking_steps: [cooking_step23, cooking_step24, cooking_step25, cooking_step26, cooking_step27, cooking_step28, cooking_step29, cooking_step30, cooking_step31], categories: [cat3, cat4, cat7], admin: admin)

recipe5 = Recipe.create(title: 'Pompoensoep met pit en bite', cooking_time: 80, intro: 'Een lekkere verwarmende soep met pittige gember en en knapperige gebakken paprika.', featured: true, published: true, week_recipe: true, cooking_steps: [cooking_step32, cooking_step33, cooking_step34, cooking_step35, cooking_step36, cooking_step37, cooking_step38, cooking_step39, cooking_step40, cooking_step41, cooking_step42], categories: [cat1, cat2, cat5, cat8, cat12], admin: admin)

photo1 = Photo.create(image: File.open('app/assets/images/citroentulband.jpg'), recipe: recipe1)
photo2 = Photo.create(image: File.open('app/assets/images/shakshuka1.jpg'), recipe: recipe2)
photo3 = Photo.create(image: File.open('app/assets/images/shakshuka2.jpg'), recipe: recipe2)
photo4 = Photo.create(image: File.open('app/assets/images/tempehburger.jpg'), recipe: recipe3)
photo5 = Photo.create(image: File.open('app/assets/images/pompoensoep.jpg'), recipe: recipe5)
photo6 = Photo.create(image: File.open('app/assets/images/chocoladetaart-demo.jpg'), recipe: recipe4)

ingredient1 = Ingredient.create(amount: '250 ml', product: product1, recipe: recipe1)
ingredient2 = Ingredient.create(amount: '1', product: product2, recipe: recipe1)
ingredient3 = Ingredient.create(amount: '80 ml', product: product3, recipe: recipe1)
ingredient4 = Ingredient.create(amount: '100 ml', product: product4, recipe: recipe1)
ingredient5 = Ingredient.create(amount: '80 ml', product: product5, recipe: recipe1)
ingredient6 = Ingredient.create(amount: '300 gr', product: product6, recipe: recipe1)
ingredient7 = Ingredient.create(amount: '2,5 tl', product: product7, recipe: recipe1)
ingredient8 = Ingredient.create(amount: '0,5 tl', product: product8, recipe: recipe1)
ingredient9 = Ingredient.create(amount: 'mespunt', product: product9, recipe: recipe1)
ingredient10 = Ingredient.create(amount: '2 dunne of 1 grote', product: product10, recipe: recipe2)
ingredient11 = Ingredient.create(amount: '300 gr', product: product11, recipe: recipe2)
ingredient12 = Ingredient.create(amount: '1 teentje', product: product12, recipe: recipe2)
ingredient13 = Ingredient.create(amount: '1 tl', product: product13, recipe: recipe2)
ingredient14 = Ingredient.create(amount: '2', product: product14, recipe: recipe2)
ingredient15 = Ingredient.create(amount: '1 el', product: product15, recipe: recipe2)
ingredient16 = Ingredient.create(amount: '50 gr', product: product16, recipe: recipe2)
ingredient17 = Ingredient.create(amount: '150 gr', product: product17, recipe: recipe3)
ingredient18 = Ingredient.create(amount: '2 el', product: product15, recipe: recipe3)
ingredient19 = Ingredient.create(amount:'200 ml', product: product18, recipe: recipe3)
ingredient20 = Ingredient.create(amount: '2,5 el', product: product19, recipe: recipe3)
ingredient21 = Ingredient.create(amount: '2 el', product: product4, recipe: recipe3)
ingredient22 = Ingredient.create(amount: '0.5 tl', product: product20, recipe: recipe3)
ingredient23 = Ingredient.create(amount:'', product: product21, recipe: recipe3)
ingredient24 = Ingredient.create(amount: '2', product: product22, recipe: recipe3)
ingredient25 = Ingredient.create(amount: 'handje', product: product23, recipe: recipe3)
ingredient26 = Ingredient.create(amount: '1', product: product24, recipe: recipe3)
ingredient27 = Ingredient.create(amount: '4', product: product25, recipe: recipe3)
ingredient28 = Ingredient.create(amount:'', product: product26, optional: true, recipe: recipe3)
ingredient29 = Ingredient.create(amount: '', product: product27, optional: true, recipe: recipe3)
ingredient30 = Ingredient.create(amount: '100 gr', product: product28, recipe: recipe4)
ingredient31 = Ingredient.create(amount: '100 gr', product: product29, recipe: recipe4)
ingredient32 = Ingredient.create(amount: '130 gr', product: product6, recipe: recipe4)
ingredient33 = Ingredient.create(amount: '60 ml', product: product4, recipe: recipe4)
ingredient34 = Ingredient.create(amount: '60 ml', product: product15, recipe: recipe4)
ingredient35 = Ingredient.create(amount: '200 gr', product: product30, recipe: recipe4)
ingredient36 = Ingredient.create(amount: '75 gr', product: product31, recipe: recipe4)
ingredient37 = Ingredient.create(amount: '', product: product32, recipe: recipe4)
ingredient38 = Ingredient.create(amount: '1', product: product33, recipe: recipe4)
ingredient39 = Ingredient.create(amount: '50 gr', product: product4, recipe: recipe4)
ingredient40 = Ingredient.create(amount: '1', product: product35, recipe: recipe5)
ingredient41 = Ingredient.create(amount: '1', product: product36, recipe: recipe5)
ingredient42 = Ingredient.create(amount: '1', product: product37, recipe: recipe5)
ingredient43 = Ingredient.create(amount: '2', product: product12, recipe: recipe5)
ingredient44 = Ingredient.create(amount: '2 cm', product: product38, recipe: recipe5)
ingredient45 = Ingredient.create(amount: '1', product: product39, recipe: recipe5)
ingredient46 = Ingredient.create(amount: '1', product: product40, recipe: recipe5)
ingredient47 = Ingredient.create(amount: 'bosje', product: product41, recipe: recipe5)
ingredient48 = Ingredient.create(amount: 'paar takjes', product: product42, recipe: recipe5)
ingredient49 = Ingredient.create(amount: '3 el', product: product15, recipe: recipe5)
ingredient50 = Ingredient.create(amount: '', product: product21, recipe: recipe5)
ingredient51 = Ingredient.create(amount: '', product: product9, recipe: recipe5)
ingredient52 = Ingredient.create(amount: 'mespunt', product: product9, recipe: recipe4)
